---
- name: Create new user
  hosts: IOS
  gather_facts: no
  connection: local

  tasks:
  - name: config new user
    ios_config:
      src: "~/NetDevOps/git-fork/ansible_proj/user.txt"
    
  - name: remove user mesh
    ios_user:
      name: mesh
      state: absent

  - name: reachability test
    ios_ping:
      dest: 10.10.10.254
      