---
- name: Gather IOS facts
  hosts: Routers
  gather_facts: no
  connection: local
  become: yes

   #vars:
   #ansible_net_username: ansible
   #ansible_net_password: cisco123

  tasks:
    - name: gather ios facts
      ios_facts:
        username: "{{ ansible_net_username }}"
        password: "{{ ansible_net_password }}"
        gather_subset: all
      register: ios_output
      when: "'Routers' in group_names"

    # - name: output ios_facts
    #   debug:
    #     var: ios_output


    - name: DISPLAY Version
      debug:
        msg: " The serial number is: {{ ansible_net_version }}"

    - name: display  serial number
      debug:
        msg: " The serial number is: {{ ansible_net_serialnum }}"
