---
- name: show version
  hosts: Routers
  gather_facts: no
  connection: local


  vars:
    ansible_net_username: ansible
    ansible_net_password: cisco123


  tasks:
    - name: show version
      ios_command:
        username: "{{ ansible_net_username }}"
        password : "{{ ansible_net_password }}"
        commands: show version
